# -*- encoding: utf-8 -*-
"""
Desc      :   Layout dataset
"""
# File    :   layout.py
# Time    :   2020/05/26 10:28:04
# Author  :   Zweien
# Contact :   278954153@qq.com

import os
from .loadresponse import LoadResponse, mat_loader, LoadResponseH5


class LayoutDataset(LoadResponse):
    """Layout dataset (mutiple files) generated by 'layout-generator'.
    """

    def __init__(
            self,
            root,
            list_path,
            subdir,
            transform=None,
            target_transform=None,
            load_name="list",
            resp_name="u",
            max_iters=None,
            nx=200,
    ):
        root = os.path.join(root, subdir)
        super().__init__(
            root,
            mat_loader,
            list_path,
            load_name=load_name,
            resp_name=resp_name,
            extensions="mat",
            transform=transform,
            target_transform=target_transform,
            max_iters=max_iters,
            nx=nx,
        )
